"""Add indexes for technology and station with year/month

Revision ID: 3c6fa30de950
Revises: 
Create Date: 2025-09-17 10:44:41.284332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6fa30de950'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guage_bill', schema=None) as batch_op:
        batch_op.alter_column('voltage_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('voltage_cost',
               existing_type=sa.TEXT(),
               type_=sa.NVARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('settlement_qty',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.NVARCHAR(length=4000),
               existing_nullable=True)

    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.alter_column('technology_main_type',
               existing_type=sa.TEXT(),
               type_=sa.NVARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('technology_bill', schema=None) as batch_op:
        batch_op.alter_column('technology_bill_percentage',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('technology_power_consump',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('technology_liquid_alum_consump',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('technology_solid_alum_consump',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('technology_chlorine_consump',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('technology_water_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_index('idx_bill_year', ['bill_year'], unique=False)
        batch_op.create_index('idx_bill_year_month', ['bill_year', 'bill_month'], unique=False)
        batch_op.create_index('idx_station_year_month', ['station_id', 'bill_year', 'bill_month'], unique=False)
        batch_op.create_index('idx_tech_year_month', ['technology_id', 'bill_year', 'bill_month'], unique=False)
        batch_op.create_index('idx_technology_id', ['technology_id'], unique=False)

    with op.batch_alter_table('voltage', schema=None) as batch_op:
        batch_op.alter_column('voltage_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('fixed_fee',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voltage', schema=None) as batch_op:
        batch_op.alter_column('fixed_fee',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('voltage_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('technology_bill', schema=None) as batch_op:
        batch_op.drop_index('idx_technology_id')
        batch_op.drop_index('idx_tech_year_month')
        batch_op.drop_index('idx_station_year_month')
        batch_op.drop_index('idx_bill_year_month')
        batch_op.drop_index('idx_bill_year')
        batch_op.alter_column('technology_water_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('technology_chlorine_consump',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('technology_solid_alum_consump',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('technology_liquid_alum_consump',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('technology_power_consump',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('technology_bill_percentage',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.alter_column('technology_main_type',
               existing_type=sa.NVARCHAR(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('guage_bill', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.NVARCHAR(length=4000),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('settlement_qty',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
        batch_op.alter_column('voltage_cost',
               existing_type=sa.NVARCHAR(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('voltage_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
